# Generated by Django 6.0.4 on 2026-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('contenu', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date', models.DateField(auto_now_add=True)),
                ('temps_lecture', models.PositiveSmallIntegerField(default=5, help_text='En minutes')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(default='fas fa-code', help_text='Classe FontAwesome', max_length=60)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
