# Generated by Django 6.0.4 on 2026-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.PositiveSmallIntegerField(default=80, help_text='0-100')),
                ('categorie', models.CharField(choices=[('linux', 'Linux & Sysadmin'), ('devops', 'DevOps & Cloud'), ('dev', 'Développement'), ('reseau', 'Réseau & Sécu'), ('autre', 'Autre')], default='linux', max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Classe FontAwesome optionnelle', max_length=60)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150)),
                ('entreprise', models.CharField(max_length=150)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=200)),
                ('etablissement', models.CharField(max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icone', models.CharField(help_text='Classe FontAwesome ex: fab fa-github', max_length=60)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('linux', 'Linux'), ('devops', 'DevOps'), ('reseau', 'Réseau'), ('cloud', 'Cloud'), ('securite', 'Sécurité'), ('ansible', 'Ansible'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('autre', 'Autre')], default='linux', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='temps_lecture',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(default='fas fa-server', max_length=60),
        ),
    ]
