# Generated by Django 6.0.4 on 2026-04-27 19:58

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_competence_experience_formation_reseausocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icone', models.CharField(default='fas fa-tag', help_text='Classe FontAwesome', max_length=60)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories Blog',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['categorie', 'ordre'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['ordre', '-date_debut'], 'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['ordre', '-date_debut'], 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='reseausocial',
            options={'ordering': ['ordre'], 'verbose_name': 'Réseau Social', 'verbose_name_plural': 'Réseaux Sociaux'},
        ),
        migrations.AddField(
            model_name='article',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description (SEO, max 160 car.)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mots-clés SEO (séparés par des virgules)'),
        ),
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Contenu complet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publie',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(verbose_name='Résumé (affiché en liste)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='temps_lecture',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minutes', verbose_name='Temps de lecture (min)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='icone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.categorie', verbose_name='Catégorie'),
        ),
    ]
