# Generated by Django 6.0.4 on 2026-04-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('prix', models.DecimalField(decimal_places=0, help_text='Prix en XOF (FCFA)', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='boutique/')),
                ('type_produit', models.CharField(choices=[('livre', 'Livre / E-book'), ('coaching', 'Coaching & Accompagnement'), ('service', 'Service Digital')], default='service', max_length=20, verbose_name='Type')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('disponible', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits / Services',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=25)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fedapay_id', models.CharField(blank=True, max_length=100, verbose_name='FedaPay ID')),
                ('fedapay_token', models.CharField(blank=True, max_length=300, verbose_name='Token paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé ✓'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Note client')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date'],
            },
        ),
    ]
